pipeline {
    agent any
     parameters {
        string(defaultValue: "http://localhost:9000", description: 'URL for SonarQube', name: 'SONAR_HOST_URL')
		string(defaultValue: "www-proxy.us.oracle.com", description: 'URL for SonarQube', name: 'PROXY_URL')
		string(defaultValue: "80", description: 'Proxy URL', name: 'PROXY_PORT')
        // choices are newline separated
        choice(choices: 'US-EAST-1\nUS-WEST-2', description: 'What AWS region?', name: 'region')
    }
    tools {
        maven 'Maven'
        jdk 'JDK 1.8'
    }
    stages {
        stage ('Checkout'){
            steps 
            {
                git (
                    url: 'https://github.com/prabuvnc/DevOpsDemo.git',
                    credentialsId: '107d9e86-3fc4-4657-b644-773cf95ca284'
                )
            }
            
            }
		stage ('Build'){
			steps
			{	
				script (
					bat "mvn clean package -DproxySet=true -DproxyHost=www-proxy.us.oracle.com -DproxyPort=80 org.sonarsource.scanner.maven:sonar-maven-plugin:3.2:sonar -Dsonar.host.url=http://localhost:9000"
				)
			}
		
		}
    }
}